### ISSUE TITLE
Create Release

### ISSUE THREAD

**Issue by gudenau** [ASTIM/OpenH264-VLC-Plugin#1]
It would be handy if you created a release, I am developing a program which uses openh264 and I could use VLC to debug data dumps.

**Comment by BilyakA** [comment]
@gudenau thanks for paying attention to the project!
Unfortunately I am developing this plugin in my free time only as we found VLC not very good optimized for our needs.
Anyway I am really happy that this plugin is needed by someone and I'll try to provide release with more options inside plugin and configure script to build it.

**Comment by BilyakA** [comment]
@gudenau check out [Releases ](https://github.com/ASTIM/OpenH264-VLC-Plugin/releases)page

**Comment by gudenau** [comment]
Great, it will be useful to debug a project!
